# Generated by Django 4.0.1 on 2022-02-10 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('sale_price', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('remaining_shares', models.IntegerField()),
                ('specific_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('rate_return', models.FloatField()),
                ('specific_number', models.CharField(max_length=20)),
                ('sale_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('interest_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('tasa_interes', models.FloatField()),
                ('cuatos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('type_financing', models.CharField(blank=True, choices=[('A', 'ACTION'), ('I', 'INVESTMENT'), ('B', 'BOND'), ('L', 'LOANS')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.TextField()),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('file', models.FileField(null=True, upload_to='documents')),
                ('name_biznes', models.TextField()),
                ('is_juridic', models.BooleanField()),
                ('is_natural', models.BooleanField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
