<<<<<<< HEAD
# Generated by Django 4.0.1 on 2022-02-08 16:29
=======
# Generated by Django 4.0.1 on 2022-02-08 16:46
>>>>>>> 7c93aa91d5beeff474ce58344afeeea1e127677d

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='user_juridic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_form', to='user.userjuridic'),
        ),
        migrations.AddField(
            model_name='requestform',
            name='user_natural',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_form', to='user.usernatural'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='project.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='request_integer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='project.requestform'),
        ),
        migrations.AddField(
            model_name='project',
            name='user_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loans',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='project.project'),
        ),
        migrations.AddField(
            model_name='investment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment', to='project.project'),
        ),
        migrations.AddField(
            model_name='documentproject',
            name='request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_project', to='project.requestform'),
        ),
        migrations.AddField(
            model_name='documentinvestment',
            name='request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_investment', to='project.requestform'),
        ),
        migrations.AddField(
            model_name='documentbond',
            name='request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_bond', to='project.requestform'),
        ),
        migrations.AddField(
            model_name='documentaction',
            name='request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_action', to='project.requestform'),
        ),
        migrations.AddField(
            model_name='bond',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bond', to='project.project'),
        ),
        migrations.AddField(
            model_name='action',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action', to='project.project'),
        ),
    ]
