# Generated by Django 4.0.1 on 2022-02-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type_financing',
            field=models.CharField(blank=True, choices=[('A', 'ACTION'), ('I', 'INVESTMENT'), ('B', 'BOND'), ('L', 'LOANS')], max_length=20),
        ),
    ]
