# Generated by Django 4.0.1 on 2022-02-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('voucher', models.ImageField(blank=True, null=True, upload_to='image')),
                ('quantity', models.IntegerField()),
                ('sale_price', models.FloatField()),
                ('total_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MyBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('voucher', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='MyInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('voucher', models.ImageField(blank=True, null=True, upload_to='image')),
                ('total_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('E', 'EVALUATION'), ('R', 'REJECTED'), ('A', 'APPROVED')], default='E', max_length=1)),
            ],
        ),
    ]
