# Generated by Django 4.0.1 on 2022-02-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaction',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
