# Generated by Django 4.0.1 on 2022-02-07 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_loans'),
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLoans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('voucher', models.ImageField(blank=True, null=True, upload_to='image')),
                ('loans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_loans', to='project.loans')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_loans', to='order.order')),
            ],
        ),
    ]
